# Generated by Django 2.1.1 on 2018-09-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest', models.IntegerField(verbose_name='ID Ресторана')),
                ('pizza', models.IntegerField(verbose_name='ID пиццы')),
                ('address', models.CharField(max_length=512, verbose_name='Адрес')),
                ('time', models.DateTimeField(verbose_name='Дата и время заказа')),
            ],
        ),
    ]
