# Generated by Django 2.1.1 on 2018-09-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
