# Generated by Django 2.1.5 on 2019-01-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrders', '0004_auto_20190121_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner_id',
            field=models.CharField(max_length=512, verbose_name='ID Владельца'),
        ),
    ]
